#!/usr/bin/env python3


import xlsxwriter

n = 0
workbook = xlsxwriter.Workbook('jobinfo.xlsx')
worksheet = workbook.add_worksheet()
with open('jobInfo', 'r') as job:
    for line in job:
        n+=1
        line = line.strip(' ')
        line_dict = line.split(" ")
        worksheet.write('A{0}'.format(n),str(line_dict[0]))
        worksheet.write('B{0}'.format(n),str(line_dict[1]))
        if len(line_dict)>=3:
            worksheet.write('C{0}'.format(n),str(line_dict[2:]))
        print('info {}:'.format(n),line_dict)
workbook.close()
print('write ok')


